# Generated by Django 5.1.1 on 2024-10-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='quantity',
            name='unit',
            field=models.CharField(choices=[('кг', 'кг'), ('л', 'л'), ('г', 'г'), ('шт', 'шт')], default='кг', max_length=255),
            preserve_default=False,
        ),
    ]
